spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username : sa
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 455781019857-u7163nq2sae1upaa5bep1mi673vd0314.apps.googleusercontent.com
            client-secret: 455781019857-u7163nq2sae1upaa5bep1mi673vd0314.apps.googleusercontent.com
            scope:
              - email
              - profile

jwt:
  issuer: joonsoung93@naver.com
  secret_key: study_springboot